// Refreshes src/abi/*.ts from the forge build (cd contracts && forge build). Written as `as const` TS so viem infers
// function, event and error types; a JSON import would lose them.
import { readFileSync, writeFileSync } from 'node:fs';

const out = new URL('../../../contracts/out/', import.meta.url);
for (const [contract, name] of [['HexitGame', 'hexitGameAbi'], ['TestUSDC', 'testUsdcAbi']]) {
  const { abi } = JSON.parse(readFileSync(new URL(`${contract}.sol/${contract}.json`, out), 'utf8'));
  writeFileSync(new URL(`../src/abi/${contract}.ts`, import.meta.url),
    `// Generated by \`npm run abi\` from contracts/out/${contract}.sol/${contract}.json. Do not edit.\n` +
    `export const ${name} = ${JSON.stringify(abi, null, 1)} as const;\n`);
}
